name: My First CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Say hello
        run: echo "Hello Amr! GitHub Actions is working!"
      - name: Show files
        run: ls -la
      - name: Show git log
        run: git log --oneline -3
